/*global d3
 */

import {ScatterPlot1D} from "../svg/scatterPlot1D";
import {cmAttributeCellVisitor} from "./cmAttributeCellVisitor"

/**
 * Visitor to preprocess per-node attributes and find valueRange.
 * This finds the value range of all attribute cells.
 */
export class cmScatterPlot1DPreprocessor extends cmAttributeCellVisitor {
  constructor(attributeIndex) {
    super(attributeIndex);
    this.values = [];
  }

  apply(cell) {
    if (this.shouldVisitCell(cell)) {
      for (var i = 0; i < cell.data.values.length; ++i) {
        this.values.push(cell.data.values[i]);
      }
    }
  }

  getValueRange() {
    return [d3.min(this.values), d3.max(this.values)];
  }
}

/**
 * Visitor to create 1D scatterplots in per-node attribute cells.
 * valueRange should be generated by the proceprocessor.
 */
export class cmScatterPlot1DVisitor extends cmAttributeCellVisitor {
  constructor(attributeIndex, radius, valueRange) {
    super(attributeIndex);
    this.radius = radius;
    this.valueRange = valueRange;
  }

  apply(cell) {
    if (this.shouldVisitCell(cell)) {
      let data = cell.data;
      let values = cell.data.values;
      let group = cell.getGroup()
        .append("g");
      if (data.isVertical) {
        new ScatterPlot1D(group, 15, 80, this.radius, values, this.valueRange, data.orientation);

        // uncomment this to create interaction group for mouse hovering
        //this.width = 15;
        //this.height = 80;
        //this.createInteractionGroup(cell);

      } else {
        new ScatterPlot1D(group, 80, 15, this.radius, values, this.valueRange, data.orientation);
      }
    }
  }
}

